name: Android

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 设置Java JDK11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: 授予权限
      run: chmod +x gradlew
    - name: 编译APK
      run: ./gradlew assembleRelease && cd app/build/outputs/apk/release && ls

    - name: 上传APK
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: app/build/outputs/apk/release/app-1.0.0-release.apk
